version: '3.6'

services:
  db:
    image: mysql:latest
    container_name: todo-api-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=asdf
    ports:
      - "9000:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    container_name: todo-api
    image: todo-api
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://todo-api-db:3306/todo
      SPRING_DATASOURCE_PASSWORD: asdf
    depends_on:
      - db
